### ISSUE TITLE
缺少app/src/main/jni/CMakeLists.txt，界面闪退

### ISSUE THREAD

**Issue by liguoyu666** [nihui/ncnn-android-squeezenet#12]
从其他ncnn例子里复制CMakeLists.txt并修改后，在手机端打开界面就闪退。其他例子能够正常运行，排除环境问题

**Comment by nihui** [comment]
已补上，感谢反馈！
https://github.com/nihui/ncnn-android-squeezenet/commit/7b1a352543dd65a184eecc18c21af07181e177ce
