### ISSUE TITLE
图片预处理resize在哪一步

### ISSUE THREAD

**Issue by liguoyu666** [nihui/ncnn-android-squeezenet#13]
1.我在pc端运行squeezenet ncnn的demo时，ncnn/examples/squeezenet.cpp图片预处理为

> https://github.com/Tencent/ncnn/blob/28bd8d5c7fcb1339132db76a1d5b0fd9643a6ec7/examples/squeezenet.cpp#L33
`ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows, 227, 227);`

将本项目运行到android studio上时，ncnn-android-squeezenet/app/src/main/jni/squeezencnn_jni.cpp图片预处理为

> https://github.com/nihui/ncnn-android-squeezenet/blob/7b1a352543dd65a184eecc18c21af07181e177ce/app/src/main/jni/squeezencnn_jni.cpp#L152-L158

我不明白为啥是先判定不等于227就返回空，我在整个cpp文件里并没有看到resize 227的代码，我理解的是应该把from_android_bitmap 换成 from_android_bitmap_resize( ....  227, 227 )。

2.ncnn读取图片的格式为什么？我自己训练的分类算法，训练时输入的图片，若用PIL读取转换为tensor的话，此处用PIXEL_BGR；若用OpenCV读取转换为tensor的话，此处用PIXEL_BGR2RGB，是否为这样？

**Comment by xingyanan** [comment]
> 1.我在pc端运行squeezenet ncnn的demo时，ncnn/examples/squeezenet.cpp图片预处理为
> 
> > https://github.com/Tencent/ncnn/blob/28bd8d5c7fcb1339132db76a1d5b0fd9643a6ec7/examples/squeezenet.cpp#L33
> > `ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows, 227, 227);`
> 
> 将本项目运行到android studio上时，ncnn-android-squeezenet/app/src/main/jni/squeezencnn_jni.cpp图片预处理为
> 
> > https://github.com/nihui/ncnn-android-squeezenet/blob/7b1a352543dd65a184eecc18c21af07181e177ce/app/src/main/jni/squeezencnn_jni.cpp#L152-L158
> 
> 我不明白为啥是先判定不等于227就返回空，我在整个cpp文件里并没有看到resize 227的代码，我理解的是应该把from_android_bitmap 换成 from_android_bitmap_resize( .... 227, 227 )。
> 
> 2.ncnn读取图片的格式为什么？我自己训练的分类算法，训练时输入的图片，若用PIL读取转换为tensor的话，此处用PIXEL_BGR；若用OpenCV读取转换为tensor的话，此处用PIXEL_BGR2RGB，是否为这样？

**Comment by ncnnnnn** [comment]
1、// resize to 227x227
yourSelectedImage = Bitmap.createScaledBitmap(rgba, 227, 227, false);

2、wiki

3、baidu

**Comment by liguoyu666** [comment]
> 1、// resize to 227x227
> yourSelectedImage = Bitmap.createScaledBitmap(rgba, 227, 227, false);
> 
> 2、wiki
> 
> 3、baidu

感谢解答， 在MainActivity.java找到了
